# Generated by Django 4.2.6 on 2023-12-20 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watershop2', '0003_alter_blog_posted_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 20, 11, 53, 20, 158742), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 20, 11, 53, 20, 159743), verbose_name='Опубликована'),
        ),
    ]
