# Generated by Django 4.2.6 on 2023-12-23 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watershop2', '0004_alter_blog_posted_alter_comment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.FileField(default='tmp.jpg', upload_to='', verbose_name='Путь к картинке'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 23, 7, 54, 41, 720125), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 23, 7, 54, 41, 720125), verbose_name='Опубликована'),
        ),
    ]
